### ISSUE TITLE
切换meta内核后TUN无法使用

### ISSUE THREAD

**Issue by IntangibleW** [kayaladream/Clash-Core-Change#2]
服务模式地球图标灰色
日志显示:
MSG->Start TUN listening error: configure tun interface: Access is denied.
![image](https://github.com/kayaladream/Clash-Core-Change/assets/43871076/7602aeaf-c6aa-46e8-a36b-df0c17390523)

**Comment by kayaladream** [comment]
是的，我刚测试了也是这样，可能meta内核不支持TUN模式？这个我也没有研究过。切换内核的脚本是不会对TUN模式有影响的

IntangibleW ***@***.***> 于2023年11月7日周二 16:31写道：

**Comment by MJRT** [comment]
我的也是灰色的, 不过服务模式的唯一用途是获取admin权限, 你直接run as admin 然后启动TUN试下

**Comment by IntangibleW** [comment]
转战Clash-verge了，关issue
